appid: wx9ccd9a18a5567939
baidu:
  clientId: GvNKmLtz2ywefRDfSC5g9VCE
  clientSecret: W9X5hGyaLmWBb6oGFsd7eHrBpFoixd1B
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: 'BASIC  '
        readTimeout: 5000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 1024
    response:
      enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-column-underline: true
    field-strategy: 1
    id-type: 0
  mapper-locations: classpath*:/mapper/*.xml
secret: 46c1f1a120f4c159e02ef2c9174e8eec
server:
  error:
    path: http://localhost:8098/user/error
  port: 8098
  servlet:
    context-path: /user
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.111:33061/yunxi_user?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: masterroot
  devtools:
    restart:
      enable: true
  redis:
    database: 0
    host: 192.168.80.121
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
    password: redispassword
    port: 6379
