server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 8087
  tomcat:
    threads:
      max: 8000
      min-spare: 1000
    max-connections: -1
    accept-count: 20000
security:
  oauth2:
    environment: http://127.0.0.1:8097
    appkey: iA0`bN0&lKJ3{vH0(
auth:
  gateway:
    shouldSkipUrls:
      - /register
      - /login/*
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  cloud:
    config:
      name: spring-cloud-gateway
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: red-package-rain-api
          uri: lb://red-package-rain-api
          predicates:
            - Path=/redPackageRainApi/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 16000000
                redis-rate-limiter.burstCapacity: 16000000
                redis-rate-limiter.requestedTokens: 1
  mvc:
    async:
      request-timeout: 20000
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  application:
    name: spring-cloud-gateway
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enable: true
  redis:
    password: admin
    database: 0
    cluster:
      nodes:
        - 192.168.80.101:6371
        - 192.168.80.101:6372
        - 192.168.80.102:6371
        - 192.168.80.102:6372
        - 192.168.80.103:6371
        - 192.168.80.103:6372
      max-redirects: 5
    timeout: 60000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 16
        min-idle: 8
        max-wait: -1
        enabled: true
