version: "3" #指定 Docker-Compose 版本
services: #定义多个 Docker 容器服务
  spring-cloud-security-oauth2: #定义服务
    build: ./ #使用 Dockerfile 构建镜像
    ports:
      - "8097:8097" #暴露端口
# 网络声明
networks:
  rmq:
    name: rmq # 指定网络名称
    driver: bridge # 指定网络驱动程序
