server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 8097
  tomcat:
    threads:
      max: 8000
      min-spare: 1000
    max-connections: -1
    accept-count: 20000
spring:
  mvc:
    async:
      request-timeout: 20000
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  application:
    name: spring-cloud-security-oauth2
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enable: true
  redis:
    password: admin
    database: 0
    cluster:
      nodes:
        - 192.168.80.101:6371
        - 192.168.80.101:6372
        - 192.168.80.102:6371
        - 192.168.80.102:6372
        - 192.168.80.103:6371
        - 192.168.80.103:6372
      max-redirects: 5
    timeout: 60000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 16
        min-idle: 8
        max-wait: -1
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.101:33061/oauth2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: node1master1root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 3000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
host:
  ip: 127.0.0.1
authjwt:
  keyPairName: jwt.jks
  keyPairAlias: jwt
  keyPairSecret: 123456
  keyPairStoreSecret: 123456