server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 8057
  tomcat:
    threads:
      max: 8000
      min-spare: 1000
    max-connections: -1
    accept-count: 20000
spring:
  mvc:
    async:
      request-timeout: 20000
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  application:
    name: red-package-rain-api
  jmx:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enable: true
  redis:
    password: admin
    database: 0
    cluster:
      nodes:
        - 192.168.80.101:6371
        - 192.168.80.101:6372
        - 192.168.80.102:6371
        - 192.168.80.102:6372
        - 192.168.80.103:6371
        - 192.168.80.103:6372
      max-redirects: 5
    timeout: 60000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 16
        min-idle: 8
        max-wait: -1
        enabled: true
rocketmq:
  name-server: 192.168.80.101:9876;192.168.80.102:9876;192.168.80.103:9876;
  producer:
    group: RedPackageRainGroup
    send-message-timeout: 5000
    retry-times-when-send-failed: 2
    max-message-size: 4194304
resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      circuitBreakerApi:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 1s
        failureRateThreshold: 20
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - java.io.IOException
  ratelimiter:
    instances:
      rateLimiterApi:
        limitForPeriod: 10000
        limitRefreshPeriod: 10s
        timeoutDuration: 500ms
        subscribeForEvents: true
        eventConsumerBufferSize: 10
filepath: D://opt
onOff: true